name: Tag Release

on:
  push:
    branches: main

jobs:
  report-with-artifacts:
    name: 'Report'
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out code'
        uses: actions/checkout@v2

      - name: 'Initialize mandatory git config'
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: 'Get new bumped version from package.json'
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master

#      - name: Extract release notes
#        id: extract_release_notes
#        uses: ffurrer2/extract-release-notes@v1
      -
      - name: Get notes
        id: generate_notes
        uses: anmarkoulis/commitizen-changelog-reader@master
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}
          changelog: CHANGELOG.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version }}
          release_name: v${{ steps.package-version.outputs.current-version }}
          body: ${{join(fromJson(steps.generate_notes.outputs.notes).notes, '')}}
          draft: false
          prerelease: false
