name: 333 Add artifact links to pull request
on:
  workflow_run:
    workflows:
      - E2E_and_Unit_Testing_Flow
      - 'E2E_and_Unit_Testing_Flow'

jobs:
  artifacts-url-comments:
    name: Add artifact links to pull request
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
