name: Build & Deploy Storybook Fix
on:
  push:
    branches:
      - 'fix/**'
  pull_request:
    branches:
      - 'fix/**'
jobs:
  build:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install NPM packages
        run: yarn install

      - name: Build project
        run: yarn build-storybook --output-dir=./fix-build

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: build-files
          path: ./fix-build


  deploy:
    name: Deploy Storubook
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-files
          path: ./fix-build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: storybook-gh-pages
          publish_dir: ./fix-build
          destination_dir: fix/${GITHUB_REF##*/}