name: Build & Deploy Storybook Fix
on:
  push:
    branches:
      - 'fix/**'
  pull_request:
    branches:
      - 'fix/**'
jobs:
  build:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF#refs/heads/}

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install NPM packages
        run: |
          npm install
          npm ci

      - name: Update browserslist
        run: npx browserslist@latest --update-db

      - name: Build project and Storybook
        run: |
          npm run build
          npm run build-storybook -- -o sb-build-files
        env:
          CI: false

      - name: Copy script file
        shell: bash
        run: cp -v ./scripts/gh-actions-branch-name-serialize.sh ./sb-build-files/gh-actions-branch-name-serialize.sh


      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: build-files
          path: ./sb-build-files

  clear_build:
    name: Clear existing build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout storybook-gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: storybook-gh-pages

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-files
          path: ./sb-build-files

      - name: Extract branch folder name
        shell: bash
        run: |
          chmod -R 777 ./scripts/gh-actions-branch-name-serialize.sh
          echo "##[set-output name=folder_name;]$GITHUB_WORKSPACE/fix/$(./sb-build-files/gh-actions-branch-name-serialize.sh "${GITHUB_REF#refs/heads/fix/}")"
        id: branch_folder_name

      - name: Remove Existing build
        uses: JesseTG/rm@v1.0.2
        with:
          path: ${{ steps.branch_folder_name.outputs.folder_name }}

      - name: Remove build files from current branch
        shell: bash
        run: rm -r ./sb-build-files

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4

  deploy:
    name: Deploy Storybook
    needs: clear_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-files
          path: ./sb-build-files

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Deploy Storybook to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: storybook-gh-pages
          publish_dir: ./sb-build-files
          destination_dir: ${{ steps.extract_branch.outputs.branch }}