name: Build & Deploy Storybook Fix
on:
  push:
    branches:
      - develop
      - 'fix/**'
  pull_request:
    branches:
      - 'fix/**'
      - develop
jobs:
  build:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Debug
        run: |
          echo ">>> GITHUB_HEAD_REF - $GITHUB_HEAD_REF"
          echo ">>> GITHUB_REF - $GITHUB_REF"
          echo ">>> GITHUB_BASE_REF - $GITHUB_BASE_REF"
          echo ">>> GITHUB_EVENT_NAME - $GITHUB_EVENT_NAME"
          echo ">>> GITHUB_REPOSITORY - $GITHUB_REPOSITORY"
          echo ">>> GITHUB_WORKSPACE - $GITHUB_WORKSPACE"

      - name: Pysh >
        if: github.event_name == 'push'
        run: echo "Push action !!! "

      - name: PR >
        if: github.event_name == 'pull_request'
        run: echo "PR action !!! "



      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install NPM packages
        run: |
          npm install
          npm ci

      - name: Update browserslist
        run: npx browserslist@latest --update-db

      - name: Build project and Storybook
        run: |
          npm run build
          npm run build-storybook -- -o sb-build-files
        env:
          CI: false

      - name: Upload name sanitize script file
        uses: actions/upload-artifact@v2
        with:
          name: sanitize-script-file
          path: ./scripts/gh-actions-branch-name-serialize.sh


      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: build-files
          path: ./sb-build-files

  clear_build:
    name: Clear existing build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout storybook-gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: ${{ secrets.GH_PAGES_BRANCH }}

      - name: Download artifact (sanitize script)
        uses: actions/download-artifact@v2
        with:
          name: sanitize-script-file
          path: ./scripts

      - name: Update script file rights
        shell: bash
        run: chmod -R 777 ./scripts/gh-actions-branch-name-serialize.sh

      - name: Extract branch folder name (Push event)
        if: github.event_name == 'push'
        shell: bash
        run: echo "##[set-output name=folder_name;]$GITHUB_WORKSPACE/$(./scripts/gh-actions-branch-name-serialize.sh "${GITHUB_REF#refs/heads/}")"
        id: branch_folder_name

      - name: Extract branch folder name (PR event)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "##[set-output name=folder_name;]$GITHUB_WORKSPACE/$(./scripts/gh-actions-branch-name-serialize.sh "$GITHUB_BASE_REF")"
        id: branch_folder_name

      - name: Remove Existing build
        uses: JesseTG/rm@v1.0.2
        if: ${{ success() }}
        with:
          path: ${{ steps.branch_folder_name.outputs.folder_name }}

      - name: Remove redundant files from the current branch
        shell: bash
        run: rm -r ./scripts

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        with:
          branch: ${{ secrets.GH_PAGES_BRANCH }}

  deploy:
    name: Deploy Storybook
    needs: clear_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact (build files)
        uses: actions/download-artifact@v2
        with:
          name: build-files
          path: ./sb-build-files

      - name: Download artifact (sanitize script)
        uses: actions/download-artifact@v2
        with:
          name: sanitize-script-file
          path: ./scripts

      - name: Extract branch name (Push event)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "##[set-output name=branch;]$(./scripts/gh-actions-branch-name-serialize.sh "${GITHUB_REF#refs/heads/}")"
        id: extract_branch

      - name: Extract branch name (PR event)
        if: github.event_name == 'pull_request'
        shell: bash
        run: echo "##[set-output name=branch;]$(./scripts/gh-actions-branch-name-serialize.sh "$GITHUB_BASE_REF")"
        id: extract_branch

      - name: Deploy Storybook to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: ${{ secrets.GH_PAGES_BRANCH }}
          publish_dir: ./sb-build-files
          destination_dir: ${{ steps.extract_branch.outputs.branch }}