name: Build & Deploy Storybook Develop
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  build:
    name: Build Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install NPM packages
        run: |
          npm install
          npm ci

      - name: Update browserslist
        run: npx browserslist@latest --update-db

      - name: Build project and Storybook
        run: |
          npm run build
          npm run build-storybook -- -o sb-build-files
        env:
          CI: false

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: build-files
          path: ./sb-build-files


  clear_build:
    name: Clear existing build
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout storybook-gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: storybook-gh-pages

      - name: Remove Existing build
        uses: JesseTG/rm@v1.0.2
        with:
          path: develop

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        with:
          branch: storybook-gh-pages

  deploy:
    name: Deploy Storubook
    needs: clear_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-files
          path: ./sb-build-files

      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_branch: storybook-gh-pages
          publish_dir: ./sb-build-files
          destination_dir: develop