#name: Build Deploy App and Storybook
name: Report demo
on:
  push:
    branches:
      - 'fix/**'
      - 'feat/**'

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        id: discord_embed_report
        env:
          app_unit_test_percentage: 5.5
          app_unit_test_diff: 0.0
        with:
          script: |
            const script = require('./.github/workflows/scripts/create-discord-report-embed-body.js')
            await script({github, context, core})

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_ALERT_UI_WEB_HOOK }}
          DISCORD_USERNAME: Basilisk-UI GH Bot
          DISCORD_EMBEDS: ${{ toJson(steps.discord_embed_report.outputs.result) }}
        uses: Ilshidur/action-discord@master

#  build-app-storybook:
#    name: Build App and Storybook
#    uses: ./.github/workflows/_called_build-app-and-storybook.yml
#    runs-on: macos-11
#    with:
#      app-build-artifact-name: app-build-files
#      storybook-build-artifact-name: sb-build-files
#      app-node-modules-cache-key: cache-node-modules-ui-app
#
#  deploy-app-storybook-builds:
#    name: Deploy App&Storybook builds
#    needs: build-app-storybook
#    uses: ./.github/workflows/_called_deploy-app-and-storybook.yml
#    runs-on: ubuntu-latest
#    if: ${{ needs.build-app-storybook.result=='success' }}
#    with:
#      app-build-artifact-name: app-build-files
#      storybook-build-artifact-name: sb-build-files
#    secrets:
#      gh_token: ${{ secrets.GH_TOKEN }}
#      gh_pages_full_branch: ${{ secrets.GH_PAGES_FULL_BRANCH }}
