#name: Build Deploy App and Storybook
name: Report demo
on:
  push:
    branches:
      - 'fix/**'
      - 'feat/**'

jobs:
  echo-input:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - uses: actions/github-script@v6
        id: discord_embed_report
        env:
          IS_APP_SB_BUILD_REPORT: true
          IS_APP_SB_DEPLOYMENT_REPORT: true
          IS_APP_UNIT_TEST_REPORT: true
          IS_APP_E2E_TEST_REPORT: false
          IS_SB_UNIT_TEST_REPORT: false
          IS_SB_E2E_TEST_REPORT: false

          APP_UNIT_TEST_PERCENTAGE: 5.5
          APP_UNIT_TEST_DIFF: 0.0
          APP_BUILD_STATUS: true
          APP_UNIT_TEST_STATUS: true
          APP_DEPLOYMENT_STATUS: true

          GITHUB_HEAD_REF: ${{ GITHUB_HEAD_REF }}
          GITHUB_REF: ${{ GITHUB_REF }}
          GITHUB_REF_NAME: ${{ GITHUB_REF_NAME }}
        with:
          result-encoding: string
          script: |
            const script = require('./scripts/ci/github-script-src/create-discord-report-embed-body.js')
            return await script({github, context, core})

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_ALERT_UI_WEB_HOOK }}
          DISCORD_USERNAME: Basilisk-UI GH Bot
          DISCORD_EMBEDS: ${{ steps.discord_embed_report.outputs.result }}
        uses: Ilshidur/action-discord@master

#  build-app-storybook:
#    name: Build App and Storybook
#    uses: ./.github/workflows/_called_build-app-and-storybook.yml
#    runs-on: macos-11
#    with:
#      app-build-artifact-name: app-build-files
#      storybook-build-artifact-name: sb-build-files
#      app-node-modules-cache-key: cache-node-modules-ui-app
#
#  deploy-app-storybook-builds:
#    name: Deploy App&Storybook builds
#    needs: build-app-storybook
#    uses: ./.github/workflows/_called_deploy-app-and-storybook.yml
#    runs-on: ubuntu-latest
#    if: ${{ needs.build-app-storybook.result=='success' }}
#    with:
#      app-build-artifact-name: app-build-files
#      storybook-build-artifact-name: sb-build-files
#    secrets:
#      gh_token: ${{ secrets.GH_TOKEN }}
#      gh_pages_full_branch: ${{ secrets.GH_PAGES_FULL_BRANCH }}
