name: Report demo

on:
  push:
    branches:
      - 'fix/**'
      - 'feat/**'
      - develop
  pull_request:
    types:
      - opened
    branches:
      - develop

jobs:
  publish-report-issue-comment:
    name: test scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload test art
        uses: actions/upload-artifact@v2
        with:
          name: test-artifacts
          path: ./scripts

      - run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token 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" \
          https://api.github.com/repos/mckrava/storybook-ci-demo/actions/workflows/21524983/dispatches \
          --data "{"ref":"develop"}"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/github-script@v6
        id: issue-comment-data
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          github-token: ${{secrets.GH_TOKEN}}
          GH_PAGES_CUSTOM_DOMAIN: ${{ secrets.GH_PAGES_CUSTOM_DOMAIN }}

          REPORT_MSG_TITLE: Test reporter
          PUBLISH_ARTIFACTS_LIST: true

          IS_APP_SB_BUILD_REPORT: true
          IS_APP_UNIT_TEST_REPORT: false
          IS_APP_E2E_TEST_REPORT: false
          IS_SB_UNIT_TEST_REPORT: false
          IS_SB_E2E_TEST_REPORT: false
          IS_APP_SB_DEPLOYMENT_REPORT: true

          APP_UNIT_TEST_PERCENTAGE: 0
          APP_UNIT_TEST_DIFF: 0
          APP_BUILD_STATUS: true
          APP_UNIT_TEST_STATUS: true

          APP_DEPLOYMENT_STATUS: true

        with:
          script: |
            const script = require('./scripts/ci/github-script-src/publish-issue-comment.js')
            return await script({github, context, core})

#      - name: Save issue comment prepared content into file
#        run: |
#          echo ${{ steps.issue-comment-data.outputs.result }} > issue-comment-data.txt
#
#      - name: Upload issue-comment-tpl
#        uses: actions/upload-artifact@v2
#        with:
#          name: issue-comment-data
#          path: ./issue-comment-data.txt