name: Report demo
#name: Report demo
on:
  pull_request:
    branches:
      - 'fix/**'
      - 'feat/**'
      - develop

jobs:
  add-dummy-artifcats:
    name: add-dummy-artifcats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload script files
        uses: actions/upload-artifact@v2
        with:
          name: script-files
          path: ./scripts


  publish-summary-report-issue-comment:
    name: test scriipts
    runs-on: ubuntu-latest
    needs: add-dummy-artifcats
    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@v6
#        env:
#          IS_APP_SB_BUILD_REPORT: ${{ inputs.app-build-pub-in-discord }}
#          IS_APP_UNIT_TEST_REPORT: ${{ inputs.app-unit-test-pub-report-in-discord }}
#          IS_APP_E2E_TEST_REPORT: false
#          IS_SB_UNIT_TEST_REPORT: false
#          IS_SB_E2E_TEST_REPORT: false
#          IS_APP_SB_DEPLOYMENT_REPORT: ${{ inputs.app-sb-deploy-pub-report-in-discord }}
#
#          APP_UNIT_TEST_PERCENTAGE: ${{ needs.app-unit-tests-codecov-pub-report.outputs.codecov_output_percentage }}
#          APP_UNIT_TEST_DIFF: ${{ needs.app-unit-tests-codecov-pub-report.outputs.codecov_output_diff }}
#
#          APP_BUILD_STATUS: ${{ inputs.app-build-status }}
#          APP_UNIT_TEST_STATUS: ${{ inputs.app-unit-test-status }}
#
#          APP_DEPLOYMENT_STATUS: ${{ inputs.app-sb-deploy-status }}

        #          GITHUB_HEAD_REF: ${{ secrets.GITHUB_HEAD_REF }}
        #          GITHUB_REF: ${{ secrets.GITHUB_REF }}
        #          GITHUB_REF_NAME: ${{ secrets.GITHUB_REF_NAME }}
        with:
          script: |
            const script = require('./scripts/ci/github-script-src/publish-issue-comment.js')
            await script({github, context, core})