name: Report demo v2

on:
  push:
    branches:
      - 'fix/**'
      - 'feat/**'
      - develop
  pull_request:
    types:
      - opened
    branches:
      - develop

jobs:
  delay:
    name: test scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Upload test art
        uses: actions/upload-artifact@v2
        with:
          name: wf_test-artifacts-v2
          path: ./scripts

#      - name: Sleep for 30 seconds
#        run: sleep 3s
#        shell: bash

  report-statuses-in-issue:
    # | Publish build and deployment statuses as pull request comment,
    # | if any pull request is associated with the latest commit.
    name: 'Report in PR'
    uses: ./.github/workflows/_called_report-status-in-issue.yml
    if: always()
    needs: delay
    with:
      publish-artifacts-list: true

      app-storybook-build-pub-report: false
      app-storybook-build-status: true

      app-storybook-deploy-pub-report: true
      app-storybook-deploy-status: true

      app-unit-test-pub-report: false
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      gh_pages_full_branch: ${{ secrets.GH_PAGES_FULL_BRANCH }}
      gh_pages_custom_domain: ${{ secrets.GH_PAGES_CUSTOM_DOMAIN }}