name: Report demo

on:
  pull_request:
    branches:
      - 'fix/**'
      - 'feat/**'
      - develop
  push:
    branches:
      - develop

jobs:
  publish-report-issue-comment:
    name: test scripts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@v6
        id: issue-comment-tpl-prepare
        env:
          gh_token: ${{ secrets.GH_TOKEN }}
          GH_PAGES_CUSTOM_DOMAIN: ${{ secrets.GH_PAGES_CUSTOM_DOMAIN }}
        with:
          script: |
            const script = require('./scripts/ci/github-script-src/prepare-publish-issue-comment-content.js')
            return await script({github, context, core})

      - name: Save issue comment prepared content into file
        run: |
          echo ${{ steps.issue-comment-tpl-prepare.outputs.result }} > issue-comment-data.txt

      - name: Upload issue-comment-tpl
        uses: actions/upload-artifact@v2
        with:
          name: issue-comment-data
          path: ./issue-comment-data.txt